### PR TITLE
extend syntax to support branches & Pull Requests

### PR DESCRIPTION
**Pull request by philschatz**
This extends the types of values that can be provided in the revision `<input>` to allow:

- partial shas: `@d34db33f`
- tag names: `@v1.2.3rc4`
- branch names: `/branch-name/with/slashes`
- Pull Requests (with the "magic" merge commit): `#123`
- Pull Requests (without the merge commit): `#123!`

Maybe it should also include a regexp to handle the full sha (instead of giving a warning)

### CODE REVIEW

**Comment by pumazi** [comment]
What about `HEAD`?

**Comment by pumazi** [comment]
You've mixed camel case with the existing snake case. 😕

**Comment by philschatz** [comment]
I was hoping to change the `<input>` default value to be `master` but it seems that is in a different file. Why use `HEAD` as an alias for `master`?

**Comment by philschatz** [comment]
Ok, @pumazi I think this is ready for review. Feel free to squash all the commits into 1.

It doesn't address the `HEAD` case but I'm hoping that the `<input>` box in rundeck could be updated to have `master` as the default value.

**Comment by philschatz** [comment]
I added support for building based on a tag name. Is there a plan for merging this code?

**Pull request merged**
